/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub type size_t = usize;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_char;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
impl ::std::default::Default for __fsid_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __qaddr_t = *mut __quad_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type FILE = _IO_FILE;
pub type __FILE = _IO_FILE;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __mbstate_t {
    pub __count: ::std::os::raw::c_int,
    pub __value: Union_Unnamed1,
}
impl ::std::default::Default for __mbstate_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct Union_Unnamed1 {
    pub _bindgen_data_: [u32; 1usize],
}
impl Union_Unnamed1 {
    pub unsafe fn __wch(&mut self) -> *mut ::std::os::raw::c_uint {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __wchb(&mut self) -> *mut [::std::os::raw::c_char; 4usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::default::Default for Union_Unnamed1 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _G_fpos_t {
    pub __pos: __off_t,
    pub __state: __mbstate_t,
}
impl ::std::default::Default for _G_fpos_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _G_fpos64_t {
    pub __pos: __off64_t,
    pub __state: __mbstate_t,
}
impl ::std::default::Default for _G_fpos64_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type va_list = __gnuc_va_list;
pub type __gnuc_va_list = __builtin_va_list;
pub enum _IO_jump_t { }
pub type _IO_lock_t = ::std::os::raw::c_void;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _IO_marker {
    pub _next: *mut _IO_marker,
    pub _sbuf: *mut _IO_FILE,
    pub _pos: ::std::os::raw::c_int,
}
impl ::std::default::Default for _IO_marker {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum __codecvt_result {
    __codecvt_ok = 0,
    __codecvt_partial = 1,
    __codecvt_error = 2,
    __codecvt_noconv = 3,
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _IO_FILE {
    pub _flags: ::std::os::raw::c_int,
    pub _IO_read_ptr: *mut ::std::os::raw::c_char,
    pub _IO_read_end: *mut ::std::os::raw::c_char,
    pub _IO_read_base: *mut ::std::os::raw::c_char,
    pub _IO_write_base: *mut ::std::os::raw::c_char,
    pub _IO_write_ptr: *mut ::std::os::raw::c_char,
    pub _IO_write_end: *mut ::std::os::raw::c_char,
    pub _IO_buf_base: *mut ::std::os::raw::c_char,
    pub _IO_buf_end: *mut ::std::os::raw::c_char,
    pub _IO_save_base: *mut ::std::os::raw::c_char,
    pub _IO_backup_base: *mut ::std::os::raw::c_char,
    pub _IO_save_end: *mut ::std::os::raw::c_char,
    pub _markers: *mut _IO_marker,
    pub _chain: *mut _IO_FILE,
    pub _fileno: ::std::os::raw::c_int,
    pub _flags2: ::std::os::raw::c_int,
    pub _old_offset: __off_t,
    pub _cur_column: ::std::os::raw::c_ushort,
    pub _vtable_offset: ::std::os::raw::c_char,
    pub _shortbuf: [::std::os::raw::c_char; 1usize],
    pub _lock: *mut _IO_lock_t,
    pub _offset: __off64_t,
    pub __pad1: *mut ::std::os::raw::c_void,
    pub __pad2: *mut ::std::os::raw::c_void,
    pub __pad3: *mut ::std::os::raw::c_void,
    pub __pad4: *mut ::std::os::raw::c_void,
    pub __pad5: size_t,
    pub _mode: ::std::os::raw::c_int,
    pub _unused2: [::std::os::raw::c_char; 20usize],
}
impl ::std::default::Default for _IO_FILE {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub enum _IO_FILE_plus { }
pub type __io_read_fn =
    ::std::option::Option<unsafe extern "C" fn(__cookie:
                                                   *mut ::std::os::raw::c_void,
                                               __buf:
                                                   *mut ::std::os::raw::c_char,
                                               __nbytes: size_t)
                              -> __ssize_t>;
pub type __io_write_fn =
    ::std::option::Option<unsafe extern "C" fn(__cookie:
                                                   *mut ::std::os::raw::c_void,
                                               __buf:
                                                   *const ::std::os::raw::c_char,
                                               __n: size_t) -> __ssize_t>;
pub type __io_seek_fn =
    ::std::option::Option<unsafe extern "C" fn(__cookie:
                                                   *mut ::std::os::raw::c_void,
                                               __pos: *mut __off64_t,
                                               __w: ::std::os::raw::c_int)
                              -> ::std::os::raw::c_int>;
pub type __io_close_fn =
    ::std::option::Option<unsafe extern "C" fn(__cookie:
                                                   *mut ::std::os::raw::c_void)
                              -> ::std::os::raw::c_int>;
pub type off_t = __off_t;
pub type ssize_t = isize;
pub type fpos_t = _G_fpos_t;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct sensors_bus_id {
    pub type_: ::std::os::raw::c_short,
    pub nr: ::std::os::raw::c_short,
}
impl ::std::default::Default for sensors_bus_id {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct sensors_chip_name {
    pub prefix: *mut ::std::os::raw::c_char,
    pub bus: sensors_bus_id,
    pub addr: ::std::os::raw::c_int,
    pub path: *mut ::std::os::raw::c_char,
}
impl ::std::default::Default for sensors_chip_name {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum sensors_feature_type {
    SENSORS_FEATURE_IN = 0,
    SENSORS_FEATURE_FAN = 1,
    SENSORS_FEATURE_TEMP = 2,
    SENSORS_FEATURE_POWER = 3,
    SENSORS_FEATURE_ENERGY = 4,
    SENSORS_FEATURE_CURR = 5,
    SENSORS_FEATURE_HUMIDITY = 6,
    SENSORS_FEATURE_MAX_MAIN = 7,
    SENSORS_FEATURE_VID = 16,
    SENSORS_FEATURE_INTRUSION = 17,
    SENSORS_FEATURE_MAX_OTHER = 18,
    SENSORS_FEATURE_BEEP_ENABLE = 24,
    SENSORS_FEATURE_MAX = 25,
    SENSORS_FEATURE_UNKNOWN = 2147483647,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum sensors_subfeature_type {
    SENSORS_SUBFEATURE_IN_INPUT = 0,
    SENSORS_SUBFEATURE_IN_MIN = 1,
    SENSORS_SUBFEATURE_IN_MAX = 2,
    SENSORS_SUBFEATURE_IN_LCRIT = 3,
    SENSORS_SUBFEATURE_IN_CRIT = 4,
    SENSORS_SUBFEATURE_IN_AVERAGE = 5,
    SENSORS_SUBFEATURE_IN_LOWEST = 6,
    SENSORS_SUBFEATURE_IN_HIGHEST = 7,
    SENSORS_SUBFEATURE_IN_ALARM = 128,
    SENSORS_SUBFEATURE_IN_MIN_ALARM = 129,
    SENSORS_SUBFEATURE_IN_MAX_ALARM = 130,
    SENSORS_SUBFEATURE_IN_BEEP = 131,
    SENSORS_SUBFEATURE_IN_LCRIT_ALARM = 132,
    SENSORS_SUBFEATURE_IN_CRIT_ALARM = 133,
    SENSORS_SUBFEATURE_FAN_INPUT = 256,
    SENSORS_SUBFEATURE_FAN_MIN = 257,
    SENSORS_SUBFEATURE_FAN_MAX = 258,
    SENSORS_SUBFEATURE_FAN_ALARM = 384,
    SENSORS_SUBFEATURE_FAN_FAULT = 385,
    SENSORS_SUBFEATURE_FAN_DIV = 386,
    SENSORS_SUBFEATURE_FAN_BEEP = 387,
    SENSORS_SUBFEATURE_FAN_PULSES = 388,
    SENSORS_SUBFEATURE_FAN_MIN_ALARM = 389,
    SENSORS_SUBFEATURE_FAN_MAX_ALARM = 390,
    SENSORS_SUBFEATURE_TEMP_INPUT = 512,
    SENSORS_SUBFEATURE_TEMP_MAX = 513,
    SENSORS_SUBFEATURE_TEMP_MAX_HYST = 514,
    SENSORS_SUBFEATURE_TEMP_MIN = 515,
    SENSORS_SUBFEATURE_TEMP_CRIT = 516,
    SENSORS_SUBFEATURE_TEMP_CRIT_HYST = 517,
    SENSORS_SUBFEATURE_TEMP_LCRIT = 518,
    SENSORS_SUBFEATURE_TEMP_EMERGENCY = 519,
    SENSORS_SUBFEATURE_TEMP_EMERGENCY_HYST = 520,
    SENSORS_SUBFEATURE_TEMP_LOWEST = 521,
    SENSORS_SUBFEATURE_TEMP_HIGHEST = 522,
    SENSORS_SUBFEATURE_TEMP_MIN_HYST = 523,
    SENSORS_SUBFEATURE_TEMP_LCRIT_HYST = 524,
    SENSORS_SUBFEATURE_TEMP_ALARM = 640,
    SENSORS_SUBFEATURE_TEMP_MAX_ALARM = 641,
    SENSORS_SUBFEATURE_TEMP_MIN_ALARM = 642,
    SENSORS_SUBFEATURE_TEMP_CRIT_ALARM = 643,
    SENSORS_SUBFEATURE_TEMP_FAULT = 644,
    SENSORS_SUBFEATURE_TEMP_TYPE = 645,
    SENSORS_SUBFEATURE_TEMP_OFFSET = 646,
    SENSORS_SUBFEATURE_TEMP_BEEP = 647,
    SENSORS_SUBFEATURE_TEMP_EMERGENCY_ALARM = 648,
    SENSORS_SUBFEATURE_TEMP_LCRIT_ALARM = 649,
    SENSORS_SUBFEATURE_POWER_AVERAGE = 768,
    SENSORS_SUBFEATURE_POWER_AVERAGE_HIGHEST = 769,
    SENSORS_SUBFEATURE_POWER_AVERAGE_LOWEST = 770,
    SENSORS_SUBFEATURE_POWER_INPUT = 771,
    SENSORS_SUBFEATURE_POWER_INPUT_HIGHEST = 772,
    SENSORS_SUBFEATURE_POWER_INPUT_LOWEST = 773,
    SENSORS_SUBFEATURE_POWER_CAP = 774,
    SENSORS_SUBFEATURE_POWER_CAP_HYST = 775,
    SENSORS_SUBFEATURE_POWER_MAX = 776,
    SENSORS_SUBFEATURE_POWER_CRIT = 777,
    SENSORS_SUBFEATURE_POWER_AVERAGE_INTERVAL = 896,
    SENSORS_SUBFEATURE_POWER_ALARM = 897,
    SENSORS_SUBFEATURE_POWER_CAP_ALARM = 898,
    SENSORS_SUBFEATURE_POWER_MAX_ALARM = 899,
    SENSORS_SUBFEATURE_POWER_CRIT_ALARM = 900,
    SENSORS_SUBFEATURE_ENERGY_INPUT = 1024,
    SENSORS_SUBFEATURE_CURR_INPUT = 1280,
    SENSORS_SUBFEATURE_CURR_MIN = 1281,
    SENSORS_SUBFEATURE_CURR_MAX = 1282,
    SENSORS_SUBFEATURE_CURR_LCRIT = 1283,
    SENSORS_SUBFEATURE_CURR_CRIT = 1284,
    SENSORS_SUBFEATURE_CURR_AVERAGE = 1285,
    SENSORS_SUBFEATURE_CURR_LOWEST = 1286,
    SENSORS_SUBFEATURE_CURR_HIGHEST = 1287,
    SENSORS_SUBFEATURE_CURR_ALARM = 1408,
    SENSORS_SUBFEATURE_CURR_MIN_ALARM = 1409,
    SENSORS_SUBFEATURE_CURR_MAX_ALARM = 1410,
    SENSORS_SUBFEATURE_CURR_BEEP = 1411,
    SENSORS_SUBFEATURE_CURR_LCRIT_ALARM = 1412,
    SENSORS_SUBFEATURE_CURR_CRIT_ALARM = 1413,
    SENSORS_SUBFEATURE_HUMIDITY_INPUT = 1536,
    SENSORS_SUBFEATURE_VID = 4096,
    SENSORS_SUBFEATURE_INTRUSION_ALARM = 4352,
    SENSORS_SUBFEATURE_INTRUSION_BEEP = 4353,
    SENSORS_SUBFEATURE_BEEP_ENABLE = 6144,
    SENSORS_SUBFEATURE_UNKNOWN = 2147483647,
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct sensors_feature {
    pub name: *mut ::std::os::raw::c_char,
    pub number: ::std::os::raw::c_int,
    pub type_: sensors_feature_type,
    pub first_subfeature: ::std::os::raw::c_int,
    pub padding1: ::std::os::raw::c_int,
}
impl ::std::default::Default for sensors_feature {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct sensors_subfeature {
    pub name: *mut ::std::os::raw::c_char,
    pub number: ::std::os::raw::c_int,
    pub type_: sensors_subfeature_type,
    pub mapping: ::std::os::raw::c_int,
    pub flags: ::std::os::raw::c_uint,
}
impl ::std::default::Default for sensors_subfeature {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
impl ::std::default::Default for __va_list_tag {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[link(name = "sensors", kind = "dylib")]
extern "C" {
    pub static mut _IO_2_1_stdin_: _IO_FILE_plus;
    pub static mut _IO_2_1_stdout_: _IO_FILE_plus;
    pub static mut _IO_2_1_stderr_: _IO_FILE_plus;
    pub static mut stdin: *mut _IO_FILE;
    pub static mut stdout: *mut _IO_FILE;
    pub static mut stderr: *mut _IO_FILE;
    pub static mut sys_nerr: ::std::os::raw::c_int;
    pub static mut sys_errlist: [*const ::std::os::raw::c_char; 0usize];
    pub static mut libsensors_version: *const ::std::os::raw::c_char;
}
#[link(name = "sensors", kind = "dylib")]
extern "C" {
    pub fn __underflow(arg1: *mut _IO_FILE) -> ::std::os::raw::c_int;
    pub fn __uflow(arg1: *mut _IO_FILE) -> ::std::os::raw::c_int;
    pub fn __overflow(arg1: *mut _IO_FILE, arg2: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn _IO_getc(__fp: *mut _IO_FILE) -> ::std::os::raw::c_int;
    pub fn _IO_putc(__c: ::std::os::raw::c_int, __fp: *mut _IO_FILE)
     -> ::std::os::raw::c_int;
    pub fn _IO_feof(__fp: *mut _IO_FILE) -> ::std::os::raw::c_int;
    pub fn _IO_ferror(__fp: *mut _IO_FILE) -> ::std::os::raw::c_int;
    pub fn _IO_peekc_locked(__fp: *mut _IO_FILE) -> ::std::os::raw::c_int;
    pub fn _IO_flockfile(arg1: *mut _IO_FILE);
    pub fn _IO_funlockfile(arg1: *mut _IO_FILE);
    pub fn _IO_ftrylockfile(arg1: *mut _IO_FILE) -> ::std::os::raw::c_int;
    pub fn _IO_vfscanf(arg1: *mut _IO_FILE,
                       arg2: *const ::std::os::raw::c_char,
                       arg3: __gnuc_va_list, arg4: *mut ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn _IO_vfprintf(arg1: *mut _IO_FILE,
                        arg2: *const ::std::os::raw::c_char,
                        arg3: __gnuc_va_list) -> ::std::os::raw::c_int;
    pub fn _IO_padn(arg1: *mut _IO_FILE, arg2: ::std::os::raw::c_int,
                    arg3: __ssize_t) -> __ssize_t;
    pub fn _IO_sgetn(arg1: *mut _IO_FILE, arg2: *mut ::std::os::raw::c_void,
                     arg3: size_t) -> size_t;
    pub fn _IO_seekoff(arg1: *mut _IO_FILE, arg2: __off64_t,
                       arg3: ::std::os::raw::c_int,
                       arg4: ::std::os::raw::c_int) -> __off64_t;
    pub fn _IO_seekpos(arg1: *mut _IO_FILE, arg2: __off64_t,
                       arg3: ::std::os::raw::c_int) -> __off64_t;
    pub fn _IO_free_backup_area(arg1: *mut _IO_FILE);
    pub fn remove(__filename: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn rename(__old: *const ::std::os::raw::c_char,
                  __new: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn renameat(__oldfd: ::std::os::raw::c_int,
                    __old: *const ::std::os::raw::c_char,
                    __newfd: ::std::os::raw::c_int,
                    __new: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn tmpfile() -> *mut FILE;
    pub fn tmpnam(__s: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn tmpnam_r(__s: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn tempnam(__dir: *const ::std::os::raw::c_char,
                   __pfx: *const ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn fclose(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn fflush(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn fflush_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn fopen(__filename: *const ::std::os::raw::c_char,
                 __modes: *const ::std::os::raw::c_char) -> *mut FILE;
    pub fn freopen(__filename: *const ::std::os::raw::c_char,
                   __modes: *const ::std::os::raw::c_char,
                   __stream: *mut FILE) -> *mut FILE;
    pub fn fdopen(__fd: ::std::os::raw::c_int,
                  __modes: *const ::std::os::raw::c_char) -> *mut FILE;
    pub fn fmemopen(__s: *mut ::std::os::raw::c_void, __len: size_t,
                    __modes: *const ::std::os::raw::c_char) -> *mut FILE;
    pub fn open_memstream(__bufloc: *mut *mut ::std::os::raw::c_char,
                          __sizeloc: *mut size_t) -> *mut FILE;
    pub fn setbuf(__stream: *mut FILE, __buf: *mut ::std::os::raw::c_char);
    pub fn setvbuf(__stream: *mut FILE, __buf: *mut ::std::os::raw::c_char,
                   __modes: ::std::os::raw::c_int, __n: size_t)
     -> ::std::os::raw::c_int;
    pub fn setbuffer(__stream: *mut FILE, __buf: *mut ::std::os::raw::c_char,
                     __size: size_t);
    pub fn setlinebuf(__stream: *mut FILE);
    pub fn fprintf(__stream: *mut FILE,
                   __format: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn printf(__format: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn sprintf(__s: *mut ::std::os::raw::c_char,
                   __format: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn vfprintf(__s: *mut FILE, __format: *const ::std::os::raw::c_char,
                    __arg: __gnuc_va_list) -> ::std::os::raw::c_int;
    pub fn vprintf(__format: *const ::std::os::raw::c_char,
                   __arg: __gnuc_va_list) -> ::std::os::raw::c_int;
    pub fn vsprintf(__s: *mut ::std::os::raw::c_char,
                    __format: *const ::std::os::raw::c_char,
                    __arg: __gnuc_va_list) -> ::std::os::raw::c_int;
    pub fn snprintf(__s: *mut ::std::os::raw::c_char, __maxlen: size_t,
                    __format: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn vsnprintf(__s: *mut ::std::os::raw::c_char, __maxlen: size_t,
                     __format: *const ::std::os::raw::c_char,
                     __arg: __gnuc_va_list) -> ::std::os::raw::c_int;
    pub fn vdprintf(__fd: ::std::os::raw::c_int,
                    __fmt: *const ::std::os::raw::c_char,
                    __arg: __gnuc_va_list) -> ::std::os::raw::c_int;
    pub fn dprintf(__fd: ::std::os::raw::c_int,
                   __fmt: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn fscanf(__stream: *mut FILE,
                  __format: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn scanf(__format: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn sscanf(__s: *const ::std::os::raw::c_char,
                  __format: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn vfscanf(__s: *mut FILE, __format: *const ::std::os::raw::c_char,
                   __arg: __gnuc_va_list) -> ::std::os::raw::c_int;
    pub fn vscanf(__format: *const ::std::os::raw::c_char,
                  __arg: __gnuc_va_list) -> ::std::os::raw::c_int;
    pub fn vsscanf(__s: *const ::std::os::raw::c_char,
                   __format: *const ::std::os::raw::c_char,
                   __arg: __gnuc_va_list) -> ::std::os::raw::c_int;
    pub fn fgetc(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn getc(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn getchar() -> ::std::os::raw::c_int;
    pub fn getc_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn getchar_unlocked() -> ::std::os::raw::c_int;
    pub fn fgetc_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn fputc(__c: ::std::os::raw::c_int, __stream: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn putc(__c: ::std::os::raw::c_int, __stream: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn putchar(__c: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn fputc_unlocked(__c: ::std::os::raw::c_int, __stream: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn putc_unlocked(__c: ::std::os::raw::c_int, __stream: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn putchar_unlocked(__c: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn getw(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn putw(__w: ::std::os::raw::c_int, __stream: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn fgets(__s: *mut ::std::os::raw::c_char, __n: ::std::os::raw::c_int,
                 __stream: *mut FILE) -> *mut ::std::os::raw::c_char;
    pub fn __getdelim(__lineptr: *mut *mut ::std::os::raw::c_char,
                      __n: *mut size_t, __delimiter: ::std::os::raw::c_int,
                      __stream: *mut FILE) -> __ssize_t;
    pub fn getdelim(__lineptr: *mut *mut ::std::os::raw::c_char,
                    __n: *mut size_t, __delimiter: ::std::os::raw::c_int,
                    __stream: *mut FILE) -> __ssize_t;
    pub fn getline(__lineptr: *mut *mut ::std::os::raw::c_char,
                   __n: *mut size_t, __stream: *mut FILE) -> __ssize_t;
    pub fn fputs(__s: *const ::std::os::raw::c_char, __stream: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn puts(__s: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
    pub fn ungetc(__c: ::std::os::raw::c_int, __stream: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn fread(__ptr: *mut ::std::os::raw::c_void, __size: size_t,
                 __n: size_t, __stream: *mut FILE) -> size_t;
    pub fn fwrite(__ptr: *const ::std::os::raw::c_void, __size: size_t,
                  __n: size_t, __s: *mut FILE) -> size_t;
    pub fn fread_unlocked(__ptr: *mut ::std::os::raw::c_void, __size: size_t,
                          __n: size_t, __stream: *mut FILE) -> size_t;
    pub fn fwrite_unlocked(__ptr: *const ::std::os::raw::c_void,
                           __size: size_t, __n: size_t, __stream: *mut FILE)
     -> size_t;
    pub fn fseek(__stream: *mut FILE, __off: ::std::os::raw::c_long,
                 __whence: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn ftell(__stream: *mut FILE) -> ::std::os::raw::c_long;
    pub fn rewind(__stream: *mut FILE);
    pub fn fseeko(__stream: *mut FILE, __off: __off_t,
                  __whence: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn ftello(__stream: *mut FILE) -> __off_t;
    pub fn fgetpos(__stream: *mut FILE, __pos: *mut fpos_t)
     -> ::std::os::raw::c_int;
    pub fn fsetpos(__stream: *mut FILE, __pos: *const fpos_t)
     -> ::std::os::raw::c_int;
    pub fn clearerr(__stream: *mut FILE);
    pub fn feof(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn ferror(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn clearerr_unlocked(__stream: *mut FILE);
    pub fn feof_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn ferror_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn perror(__s: *const ::std::os::raw::c_char);
    pub fn fileno(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn fileno_unlocked(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn popen(__command: *const ::std::os::raw::c_char,
                 __modes: *const ::std::os::raw::c_char) -> *mut FILE;
    pub fn pclose(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn ctermid(__s: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn flockfile(__stream: *mut FILE);
    pub fn ftrylockfile(__stream: *mut FILE) -> ::std::os::raw::c_int;
    pub fn funlockfile(__stream: *mut FILE);
    pub fn sensors_init(input: *mut FILE) -> ::std::os::raw::c_int;
    pub fn sensors_cleanup();
    pub fn sensors_parse_chip_name(orig_name: *const ::std::os::raw::c_char,
                                   res: *mut sensors_chip_name)
     -> ::std::os::raw::c_int;
    pub fn sensors_free_chip_name(chip: *mut sensors_chip_name);
    pub fn sensors_snprintf_chip_name(str: *mut ::std::os::raw::c_char,
                                      size: size_t,
                                      chip: *const sensors_chip_name)
     -> ::std::os::raw::c_int;
    pub fn sensors_get_adapter_name(bus: *const sensors_bus_id)
     -> *const ::std::os::raw::c_char;
    pub fn sensors_get_label(name: *const sensors_chip_name,
                             feature: *const sensors_feature)
     -> *mut ::std::os::raw::c_char;
    pub fn sensors_get_value(name: *const sensors_chip_name,
                             subfeat_nr: ::std::os::raw::c_int,
                             value: *mut f64) -> ::std::os::raw::c_int;
    pub fn sensors_set_value(name: *const sensors_chip_name,
                             subfeat_nr: ::std::os::raw::c_int, value: f64)
     -> ::std::os::raw::c_int;
    pub fn sensors_do_chip_sets(name: *const sensors_chip_name)
     -> ::std::os::raw::c_int;
    pub fn sensors_get_detected_chips(match_: *const sensors_chip_name,
                                      nr: *mut ::std::os::raw::c_int)
     -> *const sensors_chip_name;
    pub fn sensors_get_features(name: *const sensors_chip_name,
                                nr: *mut ::std::os::raw::c_int)
     -> *const sensors_feature;
    pub fn sensors_get_all_subfeatures(name: *const sensors_chip_name,
                                       feature: *const sensors_feature,
                                       nr: *mut ::std::os::raw::c_int)
     -> *const sensors_subfeature;
    pub fn sensors_get_subfeature(name: *const sensors_chip_name,
                                  feature: *const sensors_feature,
                                  type_: sensors_subfeature_type)
     -> *const sensors_subfeature;
}
